apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: cloudnative-pg
  name: system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    app.kubernetes.io/name: cloudnative-pg
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudnative-pg
    spec:
      serviceAccountName: manager
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - "/dlv"
        args:
        - "--listen=:40000"
        - "--headless=true"
        - "--api-version=2"
        - "--continue"
        - "--accept-multiclient"
        - "--log"
        - "exec"
        - "/manager"
        - "--"
        - --config-map-name=$(OPERATOR_DEPLOYMENT_NAME)-config
        - --secret-name=$(OPERATOR_DEPLOYMENT_NAME)-config
        - --webhook-port=9443
        image: controller:latest
        name: manager
        ports:
          - containerPort: 8080
            name: metrics
            protocol: TCP
        env:
        - name: OPERATOR_IMAGE_NAME
          value: $(OPERATOR_IMAGE_NAME)
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MONITORING_QUERIES_CONFIGMAP
          value: $(DEFAULT_MONITORING_CONFIGMAP)
        readinessProbe:
          httpGet:
            port: 9443
            scheme: HTTPS
            path: /readyz
        volumeMounts:
          - mountPath: /controller
            name: scratch-data
          - mountPath: /run/secrets/cnpg.io/webhook
            name: webhook-certificates
        securityContext:
          runAsUser: 10001
          runAsGroup: 10001
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - "ALL"
      volumes:
        - name: scratch-data
          emptyDir: {}
        - name: webhook-certificates
          secret:
            optional: true
            secretName: cnpg-webhook-cert
            defaultMode: 420
      terminationGracePeriodSeconds: 10
